### ISSUE TITLE
Running Error (std::bad_alloc)

### ISSUE THREAD

**Issue by charlottecc** [fwhelan/coinfinder#12]
Hi, 

I have been trying to run Coinfinder with the command `coinfinder -i gene_presence_absence.csv -I -p my_tree.newick -o coinfinder95 --associate -x 16`. 

This keeps giving me the error: 
`Reading arguments...
> CORRECTION ······· = BONFERRONI
> METHOD ··········· = COINCIDENCE
> ALT_HYPOTHESIS ··· = GREATER
> MAX_MODE ········· = ACCOMPANY
> SET_MODE ········· = FULL
> PERMIT_FILTER ···· = NO
> VERBOSE ·········· = NO
> OUTPUT_ALL ······· = NO
> FRACTION CUTOFF ·· = N/A
> SIGNIFICANCE_LEVEL = 0.05
> COMBINED_FILE ···· = gene_presence_absence.csv
> ALPHA_NAME ······· = Alpha
> BETA_NAME ········ = Beta
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted`

The csv and newick files are from Roary directly and my command seems to be the same as other people have used from these threads. 

I'd be grateful if you could shed some light on why I'm getting this error.

Thanks, 
Charlotte

**Comment by fwhelan** [comment]
Hi charlottecc,

Sorry the delay in getting back to you. This error is likely due to an issue with your `OpenMP` installation. We could work through the above; however, I've spent the last week getting `coinfinder` up on Bioconda which would make your installation easier and is (almost) guaranteed to solve this problem.

If you have conda installed you can install coinfinder with: `conda install -c conda-forge -c bioconda -c defaults coinfinder`. If you'd rather work through the above, let me know and we can go that route!

Thanks for your patience!

**Comment by charlottecc** [comment]
Hi fwhelan, 

Thank you very much for your response, I re-installed with conda and everything is working fine now!
