### ISSUE TITLE
using the -q --query flag

### ISSUE THREAD

**Issue by tslaird** [fwhelan/coinfinder#21]
I was wondering how to use the -q flag. I assume it just does pairwise tests for a specific gene (gene vs all instead of all vs. all).

How should the gene be specified (with quotes, without quotes, etc). I have been trying to use the flag in order get results for a gene of interest but it does not seem to be working.

Thanks

**Comment by fwhelan** [comment]
Hi @tslaird,

Sorry for not being able to get back to you sooner! The `-q` flag (should) work as you have assumed, yes; gene vs. all instead of all vs. all. Thanks for bringing to my attention that this wasn't working for you. I've found a bug in the code that I've fixed and am testing now, so should have this pushed to the repository for you within a few hours. The gene should be specified without quotes (e.g. `-q gene1`).

Have you used the conda or native installation route? If you've used conda, I'll push to get a new version released and up on bioconda (usually a ~24hr turnaround time).

Thanks again!

**Comment by tslaird** [comment]
Thanks! Yeah I used the conda installation

-Tyler-

**Comment by fwhelan** [comment]
Sounds good. I've started the process to get it up on conda as `v1.0.5` which hopefully shouldn't take too long. I'll post here when it's available. Thanks, @tslaird!

**Comment by fwhelan** [comment]
Hi @tslaird, `coinfinder v1.0.5` should be up on conda now with a working `-q` flag. Please feel free to reopen this issue if you have any further questions or problems with the flag!

Thanks for your patience with this.

**Comment by fwhelan** [comment]
I spoke too soon; still working on getting 1.0.5 working properly on bioconda.

**Comment by fwhelan** [comment]
`1.0.5` is finally up on bioconda!
