### ISSUE TITLE
Plans to Improve Coinfinder for smaller genome datasets

### ISSUE THREAD

**Issue by noahaus** [fwhelan/coinfinder#30]
Hello,

This isn't so much an issue, rather it is an overall question about the direction of the coinfinder software. In the paper that details coinfinder, Table 3 shows that the number of interactions diminishes as the datasets get smaller, which indicates to me that this tool is more adept at understanding datasets that have a large amount of isolates. 

However, I was wondering if there were any plans to address this feature, and out of curiosity what techniques might resolve this. This might require a sensitive answer, so if I asked this question in the wrong setting I apologize. My email is noahaus@uga.edu if this is a better place to answer this question.

**Comment by fwhelan** [comment]
Hello noahaus, thanks for your question. Unfortunately much of the reason for the results in Table 3 of the paper is statistical power. Simply, when we have less genomes as input, its harder to know whether the relationships between genes that we are seeing are biologically-significant or merely due to chance. I have been doing some reading into other ways of calculating co-occurrence which might have more statistical power with some vague plans to add these as options to coinfinder. These methods may give better results with low genome input, but I'm not sure yet. I can keep you posted, though!

And, as always, if you have any ideas or suggestions I'd be more than happy to take them on board.

**Comment by noahaus** [comment]
This is intriguing. I don't know too much on how to solve this either, and I wish you good luck in finding out!

 I will say maybe utilizing a technique called Mutual Information might be handy? It's a bit computationally slow, but it is good at deciphering associations between certain random variables, even if they are non-linear in nature. I don't know if that fixes the problems with low genome datasets however.

Thank you for answering!
